# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakthrough', '0003_auto_20160927_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='p_class',
            field=models.IntegerField(default=0),
        ),
    ]
