# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakthrough', '0004_auto_20160927_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='databank',
            name='q_class',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
