# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakthrough', '0005_databank_q_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBank1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_class', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1)),
                ('content', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataBank2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_class', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1)),
                ('content', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataBank3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_class', models.IntegerField()),
                ('q_id', models.IntegerField()),
                ('answer', models.CharField(max_length=1)),
                ('content', models.TextField()),
                ('option1', models.CharField(max_length=200)),
                ('option2', models.CharField(max_length=200)),
                ('option3', models.CharField(max_length=200)),
                ('option4', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='DataBank',
        ),
        migrations.AlterUniqueTogether(
            name='databank3',
            unique_together=set([('q_id', 'q_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='databank2',
            unique_together=set([('q_id', 'q_class')]),
        ),
        migrations.AlterUniqueTogether(
            name='databank1',
            unique_together=set([('q_id', 'q_class')]),
        ),
    ]
